<?php
/**
 * Created by IntelliJ IDEA.
 * User: Utilisateur
 * Date: 19/12/2017
 * Time: 20:20
 */

namespace Test\Unit\App;

use App\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}
